version: '3.3'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.1
    ports:
      - "2379:2379"
    command: etcd --advertise-client-urls http://0.0.0.0:2379 --listen-client-urls http://0.0.0.0:2379

  api-gateway:
    build: .
    environment:
      - ETCD_HOSTS=etcd:2379
    depends_on:
      - etcd
